name: flutter_timezone
description: A flutter plugin for getting the local timezone of the device.
version: 1.0.9
homepage: https://github.com/tjarvstrand/flutter_timezone

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: ">=3.7.10"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: net.wolverinebeach.flutter_timezone
        pluginClass: FlutterTimezonePlugin
      ios:
        pluginClass: FlutterTimezonePlugin
